name: CI Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Using a container for all steps in this job
    container: python:3.9-slim

    steps:
      - name: Checkout
        # Uses an external action to check out the code
        uses: actions/checkout@v3
      - name: Install dependencies
        # Runs commands inside the specified 'container'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with Flake8
        # Runs commands to lint
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        # Runs commands to standardize code
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app